### PR TITLE
Move the codebase from the inital repository

### PR DESCRIPTION
**Pull request by knightburton**
This codebase come from [the inital development repository](https://github.com/knightburton/vscode-iotjs-debug). All commits are signed-off, tested by Travis-CI and has at least one code review.

### CODE REVIEW

**Comment by knightburton** [comment]
This PR is a bit huge, I know that, however we would like to keep the history for traceability. IMO, this PR should be rebased and merged with these commits.

**Review by Yuyupo — APPROVED** [review]
LGTM (informal)

**Review by yichoi — APPROVED** [review]
LGTM

**Comment by yichoi** [comment]
@daeyeon please enable CI for this repo

**Comment by yichoi** [comment]
Oops. I squashed!. Is it what you want? @knightburton 
If not, @daeyeon git reset HEAD^ and force push then @knightburton raise PR again

**Comment by knightburton** [comment]
@yichoi I wanted to keep the history, the reset would be great.

**Comment by daeyeon** [comment]
@knightburton the master has been reverted. Could you please make this pr again?

**Comment by knightburton** [comment]
@daeyeon I've opened it.

**Pull request merged**
