### PR TITLE
Add multiple source handling to extension

### PR DESCRIPTION
**Pull request by tdusnoki**
IoT.js-VSCode-DCO-1.0-Signed-off-by: Tibor Dusnoki tdusnoki@inf.u-szeged.hu

### CODE REVIEW

**Review by robertsipka — APPROVED** [review]
Nice patch, ~~LGTM~~

**Review by LaszloLango — APPROVED** [review]
LGTM

**Review by robertsipka — CHANGES_REQUESTED** [review]
A small request before we merge this patch:
Please write a description of the order in which the source files should be selected.

**Review by robertsipka — APPROVED** [review]
LGTM

**Pull request merged**
