### PR TITLE
Change the signed-off message template

### PR DESCRIPTION
**Pull request by knightburton**
IoT.js-VSCode-DCO-1.0-Signed-off-by: Imre Kiss kissi.szeged@partner.samsung.com

### CODE REVIEW

**Review by yichoi — APPROVED** [review]
LGTM

**Comment by daeyeon** [comment]
This looks good to me. However, can you add a fix for the typo in README also? 
`IoT.js Code is Open Source ....` -> `IoT.js VSCode extension is Open Source ....`

**Review by daeyeon — APPROVED** [review]
@knightburton Thanks!

**Comment by daeyeon** [comment]
Closed due to the master reset.

**Pull request closed without merging**
